const mockCategories = [
  'technique',
  'nutrition',
  'gear',
  'training',
  'fitness',
  'swimming',
  'open-water',
  'masters-swimming',
  'competitions',
  'swim-safety',
  'swim-lessons',
];

const mockTags = [
  'swimming techniques',
  'swim workouts',
  'swim drills',
  'open water swimming',
  'swim gear',
  'goggles',
  'swimwear',
  'swim caps',
  'swimming accessories',
  'swim training tools',
  'fitness',
  'strength training',
  'cardiovascular training',
  'flexibility',
  'injury prevention',
  'recovery',
  'nutrition',
  'hydration',
  'sports supplements',
  'meal planning',
  'pre-workout meals',
  'post-workout meals',
  'healthy snacks',
  'weight loss',
  'weight gain',
  'running',
  'cycling',
  'triathlon',
  'cross-training',
  'outdoor activities',
  'speed',
  'endurance',
  'training',
  'balance',
  'masters swimming',
  'swim meets',
  'swim clubs',
  'swim safety',
  'drowning prevention',
  'lifeguarding',
  'swim lessons',
  'learn to swim',
  'swim coaching',
];

module.exports = {
  mockCategories,
  mockTags,
};
